import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

import ReactQueryProvider from "@/components/react-query-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={cn(inter.className, "min-h-screen")}>
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
          <SpeedInsights />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
